---
- name: Playbook pour dire coucou avec une variable
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Dire coucou au monde avec une variable
      ansible.builtin.debug:
        msg: "coucou monde {{ tunnel_name }}"
